### PR TITLE
fix: improve path handling and file system operations for cross-platform compatibility

### LINKED ISSUE #8: !! Support Windows !!
Currently tried using this on a project on windows and it's failing in mysterious ways, although working expected on linuix

### PR DESCRIPTION
**Pull request by Anshgrover23**
@algora-pbc /claim #8
Fixes #8

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import glob from "glob-promise"
 import mkdirp from "mkdirp"
-import path from "path/posix"
+import path from "path"
```
Comment (seveibar) [inline src/index.ts:3]: we should still use path/posix here if i understand your implementation properly

Comment (seveibar) [reply src/index.ts:3]: oh maybe not

File: src/index.ts [hunk 2]
```diff
@@ -51,23 +64,38 @@ export const getMatchingFilePaths = async ({
...
-    vfs[filePath] = await fs.readFile(path.resolve(dirPath, filePath))
-    if (contentFormat === "string") {
-      vfs[filePath] = vfs[filePath].toString()
+    try {
+      const fullPath = path.join(dirPath, filePath)
+      const content = await fs.readFile(fullPath)
+      const normalizedPath = toPosixPath(filePath)
+      vfs[normalizedPath] = content.toString()
+    } catch (err) {
+      console.error(`Failed to read file ${filePath}:`, err)
```
Comment (seveibar) [inline src/index.ts]: don't silent error! remove this

Comment (seveibar) [reply src/index.ts]: i guess it's not a silent error but it will still be ignored and cause issues. Try improving the error message etc. but don't just ignore errors unless the user specifies to do so

**Review by seveibar — APPROVED** [review]
see my requested change

**Comment by ArnavK-09** [comment]
Tests are failing, revamp needed?
